version: "3.7"

services:
  fastapi-app:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "5001:5001"
    depends_on:
      - loki
    environment:
      - LOKI_ENDPOINT=http://loki:3100/loki/api/v1/push

  jmeter:
    build:
      context: ./jmeter
      dockerfile: Dockerfile
    container_name: jmeter
    volumes:
      - ./jmeter:/jmeter
    command:
      - jmeter
      - -n
      - -t
      - /jmeter/fastapi_test_plan.jmx
      - -l
      - /jmeter/results.jtl
      - -JBASE_URL=http://fastapi-app:5001
      - -Jjmeter.save.saveservice.output_format=csv
      - -e
      - -o
      - /jmeter/report

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "7070:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "7100:9100"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  grafana-data:
